### ISSUE TITLE
Incluir un fichero de datos de agentes en la ruta: 'doc/tests/examples/agents.xlsx'

### ISSUE THREAD

**Issue by kilianpg** [Arquisoft/Loader_e3b#11]
La idea es incluir una muestra variada (Persona, Sensor, etc) que incluya la mayoría de posibilidades y que se reutilicen a la hora de probar el resto de módulos. Estaría bien además generar un tabla en formato Markdown con esos datos par poder incluirla en los README de cada módulo, algo así: [Datos usuarios de prueba](https://github.com/Arquisoft/InciManager_e3b#datos-usuarios-de-prueba).

**Comment by UO244730** [comment]
Ya está solucionado. Confírmame que no hay ningún problema antes de cerrar la issue.
