### ISSUE TITLE
README con pasos para ejecutar la aplicación

### ISSUE THREAD

**Issue by dalvgui** [Arquisoft/Loader_e3b#14]
Formalizar en el README también, la secuencia de pasos del módulo sin depender de eclipse para desplegar el proyecto y realizar la carga de agentes.

**Comment by UO244730** [comment]
¿Borro también las instrucciones para ejecutar desde Eclipse o las dejo?

**Comment by miguelms95** [comment]
Toda la documentación es bienvenida. Yo creo que puedes  dejarlo en un apartado "como ejecutar desde eclipse", pero que no falte la **documentación para ejecutar desde línea de comandos** .

**Comment by miguelms95** [comment]
Necesito esos pasos para ejecutar la aplicación en línea de comandos (sin depender de eclipse), para el testeo de la integración.

**Comment by kilianpg** [comment]
El PullRequest #18 incorpora las modificaciones necesarias para poder ejecutar la aplicación con el plugin Exec Maven Plugin:

~~~
mvn exec:java
mvn exec:java -Dexec.args="load src/test/resources/agents.xlsx"
~~~

Aunque se trata de algo equivalente a `mvn spring-boot:run` la forma más lógica de ejecutarlo una vez desplegado es invocar directamente al fichero jar generado:

~~~
mvn clean install -U
java -jar target/Loader_e3b-0.0.1-jar-with-dependencies.jar load src/test/resources/agents.xlsx
~~~

P.D: Me acabo de fijar que en lugar de mostrar solo las lineas modificadas del POM, muestra todo el fichero. Creo que se trata de un problema con la gestión del carácter fin de linea y la utilización de diferentes plataformas (Windows/GNU-Linux). Las lineas modificadas son las que contienen el literal 'main.LoadUsers'
