### ISSUE TITLE
Base de datos hsqldb

### ISSUE THREAD

**Issue by miguelms95** [Arquisoft/Loader_e3b#17]
Tenéis que utilizar la base de datos HSQLDB, para la integración con el resto de los módulos.

En vuestro [properties](https://github.com/Arquisoft/Loader_e3b/blob/master/src/main/resources/application.properties) está configurado una BD mysql en un host del año pasado (si no me equivoco): `jdbc:mysql://bd.koinsys.es:3306/asw1a_bd`

Hay que cambiar la dependencia del POM.xml a hsqldb, como en InciDashboard ([ver aquí](https://github.com/Arquisoft/InciDashboard_e3b/blob/master/pom.xml)), y quitar la de mysql, y editar el .properties para dejarlo que se conecte a hsqldb

**Comment by pablosky5** [comment]
Añadi la dependencia al pom [Loader_e3b/pom.xml] y cambie el fichero properties [Loader_e3b/src/main/resources/application.properties] para que se conecte a la base hsqldb correctamente.

**Comment by pablosky5** [comment]
Añadi la dependencia al [pom] (Loader_e3b/pom.xml) y cambie el fichero [properties] (Loader_e3b/src/main/resources/application.properties) para que se conecte a la base hsqldb correctamente.

**Comment by pablosky5** [comment]
Añadi la dependencia al [pom](Loader_e3b/pom.xml) y cambie el fichero [properties](Loader_e3b/src/main/resources/application.properties) para que se conecte a la base hsqldb correctamente.

**Comment by dalvgui** [comment]
Para la integracion respecto los demas modulos hemos acordado al final usar Postgresql, esta issue ya no es necesaria.
