### ISSUE TITLE
Eliminar dependencias no usadas

### ISSUE THREAD

**Issue by UO244730** [Arquisoft/Loader_e3b#22]
El POM sigue incluyendo dependencias de mySQL, HSQLDB y posiblemente otras que ya no son utilizadas. Arreglar.

**Comment by dalvgui** [comment]
Eliminar la dependencia mysql ahora usamos postgresql.

**Comment by dalvgui** [comment]
Tras los commit 6c4f3b14229a52a12ddebb3ba6f90e931c67ae0e, 90aa990546b89563a5d7b61679ecc0a3db1d20f6 , 284207f89416931d481201a08544489ae4b48af7 , 4218392c97bab5e64e643982f9a26ced924847ea al master esta issue estaría cerrada
