### ISSUE TITLE
No se encuentra archivo Excel

### ISSUE THREAD

**Issue by UO244730** [Arquisoft/Loader_e3b#7]
Al ejecutar aparece el siguiente error:
`No se ha encontrado el archivo excel especificado.
feb 17, 2018 10:14:51 PM reportwriter.WriteReportImpl log
ADVERTENCIA: No se ha encontrado el archivo excel`
La primera vez no apareció y todo funcionó perfectamente, al volver a hacerlo da este error.

**Comment by dalvgui** [comment]
Es posible que le estés indicando la  ruta equivocada, tienes que indicarle en el argumento al 'main' la ruta completa del tipo :  
C:\XXX\XXX\XXX\ASW_proyecto\workspace\Loader_e3b\src\test\resources\test.xlsx
Y el test.xlsx será el excel a procesar.
